date_time: "%I:%M%p %m/%d/%Y"
date_format: "%Y-%m-%d"
hours: "%H:%m"
per_page: 5
avatar_size: 50
word_per_lesson: 5
answer_number: 3
avatar_small: 30
activity_size: 5
lesson_size: 1
options:
  - all_words
  - learnt
  - not_yet
user:
  per_page: 10
all: "All category"
